package com.dpashko.localaiclient.domain.models.conversation

/**
 * Chat participant role used by local provider request payloads and UI rendering.
 */
enum class MessageRole {
    /** System instruction prepended to provider context when configured. */
    SYSTEM,
    /** Message written by the app user. */
    USER,
    /** Message generated by a local AI model. */
    ASSISTANT,
}
